# Generated by Django 4.0.4 on 2022-05-14 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registration')),
            ],
            options={
                'db_table': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=99999)),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.contacts')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registration')),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
    ]
