# Generated by Django 4.0.4 on 2022-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_messages_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.CharField(max_length=15),
        ),
    ]
