# Generated by Django 4.0.4 on 2022-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('userimage', models.ImageField(upload_to='users/')),
                ('password', models.CharField(max_length=366)),
                ('is_active', models.BooleanField(default=True)),
                ('logedin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
