# Generated by Django 4.0.4 on 2022-05-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
